//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeppApp.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SeppApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AlertMessageDataPrivacyConsentRemove {
            get {
                return ResourceManager.GetString("AlertMessageDataPrivacyConsentRemove", resourceCulture);
            }
        }
        
        internal static string AlertTitleDataPrivacyConsentRemove {
            get {
                return ResourceManager.GetString("AlertTitleDataPrivacyConsentRemove", resourceCulture);
            }
        }
        
        internal static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }
        
        internal static string ButtonOkText {
            get {
                return ResourceManager.GetString("ButtonOkText", resourceCulture);
            }
        }
        
        internal static string ButtonTextDataPrivacyConsentRemove {
            get {
                return ResourceManager.GetString("ButtonTextDataPrivacyConsentRemove", resourceCulture);
            }
        }
        
        internal static string DataPrivacyMainText {
            get {
                return ResourceManager.GetString("DataPrivacyMainText", resourceCulture);
            }
        }
        
        internal static string DataPrivacyPageTitle {
            get {
                return ResourceManager.GetString("DataPrivacyPageTitle", resourceCulture);
            }
        }
        
        internal static string ImpressumMainText {
            get {
                return ResourceManager.GetString("ImpressumMainText", resourceCulture);
            }
        }
        
        internal static string ImpressumPageTitle {
            get {
                return ResourceManager.GetString("ImpressumPageTitle", resourceCulture);
            }
        }
        
        internal static string LabelGameHintMaibaumkraxeln {
            get {
                return ResourceManager.GetString("LabelGameHintMaibaumkraxeln", resourceCulture);
            }
        }
        
        internal static string LabelGameHintMaibaumKraxelnBad {
            get {
                return ResourceManager.GetString("LabelGameHintMaibaumKraxelnBad", resourceCulture);
            }
        }
        
        internal static string LabelGameHintMaibaumKraxelnOk {
            get {
                return ResourceManager.GetString("LabelGameHintMaibaumKraxelnOk", resourceCulture);
            }
        }
        
        internal static string LabelGameHintMaibaumKraxelnSuper {
            get {
                return ResourceManager.GetString("LabelGameHintMaibaumKraxelnSuper", resourceCulture);
            }
        }
        
        internal static string LabelGameHintOachkatzlSchwoaf {
            get {
                return ResourceManager.GetString("LabelGameHintOachkatzlSchwoaf", resourceCulture);
            }
        }
        
        internal static string LabelGameHintOachkatzlSchwoafBad {
            get {
                return ResourceManager.GetString("LabelGameHintOachkatzlSchwoafBad", resourceCulture);
            }
        }
        
        internal static string LabelGameHintOachkatzlSchwoafGood {
            get {
                return ResourceManager.GetString("LabelGameHintOachkatzlSchwoafGood", resourceCulture);
            }
        }
        
        internal static string LabelGameHintOachkatzlSchwoafSolid {
            get {
                return ResourceManager.GetString("LabelGameHintOachkatzlSchwoafSolid", resourceCulture);
            }
        }
        
        internal static string LabelGameHintOachkatzlSchwoafTop {
            get {
                return ResourceManager.GetString("LabelGameHintOachkatzlSchwoafTop", resourceCulture);
            }
        }
        
        internal static string LabelGameInstructions {
            get {
                return ResourceManager.GetString("LabelGameInstructions", resourceCulture);
            }
        }
        
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        internal static string SplashWelcome {
            get {
                return ResourceManager.GetString("SplashWelcome", resourceCulture);
            }
        }
        
        internal static string SplashWelcomeAddExplaination {
            get {
                return ResourceManager.GetString("SplashWelcomeAddExplaination", resourceCulture);
            }
        }
        
        internal static string ToastErrorMicrophoneAccessMissing {
            get {
                return ResourceManager.GetString("ToastErrorMicrophoneAccessMissing", resourceCulture);
            }
        }
    }
}
