//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeppApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeppApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to withdraw your consent to data protection? This app can only be fully used if data protection consent is accepted..
        /// </summary>
        internal static string AlertMessageDataPrivacyConsentRemove {
            get {
                return ResourceManager.GetString("AlertMessageDataPrivacyConsentRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Remove data privacy consent?.
        /// </summary>
        internal static string AlertTitleDataPrivacyConsentRemove {
            get {
                return ResourceManager.GetString("AlertTitleDataPrivacyConsentRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOkText {
            get {
                return ResourceManager.GetString("ButtonOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Consent.
        /// </summary>
        internal static string ButtonTextDataPrivacyConsentRemove {
            get {
                return ResourceManager.GetString("ButtonTextDataPrivacyConsentRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy of Red Valley Software GmbH for the App “An Sepp sei App”  
        ///Effective Date: September 2025
        ///
        ///Protecting your personal data is a key concern for us.  
        ///This privacy policy informs you about the processing of your personal data in connection with the use of the “An Sepp sei App” in accordance with applicable data protection laws:
        ///
        ///- EU General Data Protection Regulation (GDPR)  
        ///- Revised Swiss Data Protection Act (revDSG)  
        ///- UK GDPR and Data Protection Act 2018  
        ///- Privacy and Electron [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataPrivacyMainText {
            get {
                return ResourceManager.GetString("DataPrivacyMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data privacy.
        /// </summary>
        internal static string DataPrivacyPageTitle {
            get {
                return ResourceManager.GetString("DataPrivacyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Notice:
        ///Information according to Section 5 of the German Telemedia Act (TMG):
        ///Responsible company:
        ///Red Valley Software GmbH
        ///Headquarters: Am Pumperhölzl 12, 84323 Massing
        ///The company is registered in the commercial register and is a member of the Lower Bavaria Chamber of Industry and Commerce (IHK) (ihk@passau.ihk.de).
        ///Telephone: +49 8724 2071850
        ///E-Mail: rupert.eder@redvalley-software.com
        ///Website: www.redvalley-software.com
        ///Management: Rupert Eder
        ///Registration number: HRB 11508
        ///VAT identifi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImpressumMainText {
            get {
                return ResourceManager.GetString("ImpressumMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        internal static string ImpressumPageTitle {
            get {
                return ResourceManager.GetString("ImpressumPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the squirrel to start the game.
        ///Sepp will pronounce the word correctly first — listen carefully! 
        ///Then it&apos;s your turn: 
        ///try to repeat the word as accurately as possible to earn the highest score you can..
        /// </summary>
        internal static string LabelGameHintOachkatzlSchwoaf {
            get {
                return ResourceManager.GetString("LabelGameHintOachkatzlSchwoaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ No Reward – 0 Coins
        ///
        ///Looks like it wasn’t your best run... No coins this time, but chin up – next round is your chance to shine! 
        ///
        ///Just tap the squirrel to start a new round..
        /// </summary>
        internal static string LabelGameHintOachkatzlSchwoafBad {
            get {
                return ResourceManager.GetString("LabelGameHintOachkatzlSchwoafBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥈 Great Job – 10 Coins
        ///
        ///Strong performance! You were close to the top. You’ve earned 10 coins for your effort. Tap the squirrel to show what you’ve got in the next round!.
        /// </summary>
        internal static string LabelGameHintOachkatzlSchwoafGood {
            get {
                return ResourceManager.GetString("LabelGameHintOachkatzlSchwoafGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥉 Decent Effort – 5 Coins
        ///
        ///Not bad! You held your ground. You get 5 coins for your determination – keep going, practice makes champions! 
        ///
        ///One tap on the squirrel, and you&apos;re back in the game!.
        /// </summary>
        internal static string LabelGameHintOachkatzlSchwoafSolid {
            get {
                return ResourceManager.GetString("LabelGameHintOachkatzlSchwoafSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇 Top Performance – 20 Coins
        ///
        ///Wow! You nailed it like a true pro. Your skills are impressive – you’ve earned a whopping 20 coins as a reward. 
        ///
        ///Tap the squirrel to jump straight into the next round!.
        /// </summary>
        internal static string LabelGameHintOachkatzlSchwoafTop {
            get {
                return ResourceManager.GetString("LabelGameHintOachkatzlSchwoafTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Instructions:.
        /// </summary>
        internal static string LabelGameInstructions {
            get {
                return ResourceManager.GetString("LabelGameInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Sepp sei App.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Talking Sepp Pro, the game starts immediately....
        /// </summary>
        internal static string SplashWelcome {
            get {
                return ResourceManager.GetString("SplashWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is ad-supported 😉, the game starts immediately after the following advertisement....
        /// </summary>
        internal static string SplashWelcomeAddExplaination {
            get {
                return ResourceManager.GetString("SplashWelcomeAddExplaination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Access Missing:
        ///Please enable microphone permission to play the game..
        /// </summary>
        internal static string ToastErrorMicrophoneAccessMissing {
            get {
                return ResourceManager.GetString("ToastErrorMicrophoneAccessMissing", resourceCulture);
            }
        }
    }
}
